<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Ron Viejo de Caldas Tradicional',
                'slug' => 'ron-viejo-de-caldas-tradicional',
                'description' => 'despues la añado',
                'short_description' => null,
                'alcohol_percentage' => 35.00,
                'type' => 'a',
                'age' => '3',
                'origin_country' => 'Caldas',
                'volume' => '375',
                'price' => 55000.00,
                'discount_price' => 0.00,
                'stock' => 24,
                'min_stock' => 1,
                'meta_title' => null,
                'meta_description' => null,
                'meta_keywords' => 'tradicional',
                'is_active' => 1,
                'is_featured' => 0,
                'is_new' => 0,
                'is_on_sale' => 0,
                'views' => 0,
                'rating' => 5.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'category_id' => 9,
                'brand_id' => 3,
                'name' => 'Aguardiente Antiqueño Tapa Azul',
                'slug' => 'aguardiente-antioqueno-tapa-azul',
                'description' => 'Aguardiente tradicional colombiano elaborado con anís, suave y seco.',
                'short_description' => 'Aguardiente clásico paisa',
                'alcohol_percentage' => 29.00,
                'type' => 'Aguardiente',
                'age' => null,
                'origin_country' => 'Colombia',
                'volume' => '750ml',
                'price' => 45000.00,
                'discount_price' => null,
                'stock' => 100,
                'min_stock' => 10,
                'meta_title' => 'Aguardiente Antiqueño',
                'meta_description' => 'Licor colombiano tradicional',
                'meta_keywords' => 'aguardiente,antioquia,licor',
                'is_active' => 1,
                'is_featured' => 1,
                'is_new' => 1,
                'is_on_sale' => 1,
                'views' => 1,
                'rating' => 5.00,
                'reviews_count' => 3,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'brand_id' => 7,
                'name' => 'Ron Medellín Añejo 3 Años',
                'slug' => 'ron-medellin-anejo-3-anos',
                'description' => 'Ron añejado en barricas de roble por 3 años, sabor suave y notas dulces.',
                'short_description' => 'Ron añejo suave',
                'alcohol_percentage' => 35.00,
                'type' => 'Ron',
                'age' => '3',
                'origin_country' => 'Colombia',
                'volume' => '750ml',
                'price' => 65000.00,
                'discount_price' => 59000.00,
                'stock' => 80,
                'min_stock' => 10,
                'meta_title' => 'Ron Medellín 3 años',
                'meta_description' => 'Ron colombiano añejo',
                'meta_keywords' => 'ron,medellin,anejo',
                'is_active' => 1,
                'is_featured' => 1,
                'is_new' => 0,
                'is_on_sale' => 1,
                'views' => 0,
                'rating' => 0.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'brand_id' => 7,
                'name' => 'Ron Medellín Gran Reserva 8 Años',
                'slug' => 'ron-medellin-gran-reserva-8-anos',
                'description' => 'Ron premium con 8 años de añejamiento, aroma intenso y sabor profundo.',
                'short_description' => 'Ron premium reserva',
                'alcohol_percentage' => 40.00,
                'type' => 'Ron',
                'age' => '8',
                'origin_country' => 'Colombia',
                'volume' => '750ml',
                'price' => 120000.00,
                'discount_price' => null,
                'stock' => 50,
                'min_stock' => 5,
                'meta_title' => 'Ron Medellín Gran Reserva',
                'meta_description' => 'Ron colombiano premium',
                'meta_keywords' => 'ron,reserva,premium',
                'is_active' => 1,
                'is_featured' => 1,
                'is_new' => 0,
                'is_on_sale' => 0,
                'views' => 0,
                'rating' => 0.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'category_id' => 9,
                'brand_id' => null,
                'name' => 'Aguardiente Néctar Rojo',
                'slug' => 'aguardiente-nectar-rojo',
                'description' => 'Aguardiente con sabor más suave y ligeramente dulce.',
                'short_description' => 'Aguardiente suave',
                'alcohol_percentage' => 24.00,
                'type' => 'Aguardiente',
                'age' => null,
                'origin_country' => 'Colombia',
                'volume' => '750ml',
                'price' => 42000.00,
                'discount_price' => null,
                'stock' => 90,
                'min_stock' => 10,
                'meta_title' => 'Néctar Rojo',
                'meta_description' => 'Aguardiente colombiano suave',
                'meta_keywords' => 'nectar,aguardiente,bogota',
                'is_active' => 0,
                'is_featured' => 0,
                'is_new' => 1,
                'is_on_sale' => 0,
                'views' => 0,
                'rating' => 0.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Crema de Ron Viejo de Caldas',
                'slug' => 'crema-de-ron-viejo-de-caldas',
                'description' => 'Licor cremoso a base de ron, ideal para postres y cócteles.',
                'short_description' => 'Licor cremoso de ron',
                'alcohol_percentage' => 16.00,
                'type' => 'Crema',
                'age' => null,
                'origin_country' => 'Colombia',
                'volume' => '700ml',
                'price' => 55000.00,
                'discount_price' => null,
                'stock' => 60,
                'min_stock' => 8,
                'meta_title' => 'Crema de Ron Viejo de Caldas',
                'meta_description' => 'Licor cremoso colombiano',
                'meta_keywords' => 'crema,ron,caldas',
                'is_active' => 1,
                'is_featured' => 0,
                'is_new' => 0,
                'is_on_sale' => 0,
                'views' => 0,
                'rating' => 0.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'category_id' => 9,
                'brand_id' => null,
                'name' => 'Aguardiente Blanco del Valle',
                'slug' => 'aguardiente-blanco-del-valle',
                'description' => 'Aguardiente del Valle del Cauca con sabor seco y tradicional.',
                'short_description' => 'Aguardiente del valle',
                'alcohol_percentage' => 29.00,
                'type' => 'Aguardiente',
                'age' => null,
                'origin_country' => 'Colombia',
                'volume' => '750ml',
                'price' => 43000.00,
                'discount_price' => 39000.00,
                'stock' => 75,
                'min_stock' => 10,
                'meta_title' => 'Blanco del Valle',
                'meta_description' => 'Aguardiente colombiano del valle',
                'meta_keywords' => 'valle,aguardiente,blanco',
                'is_active' => 0,
                'is_featured' => 0,
                'is_new' => 0,
                'is_on_sale' => 1,
                'views' => 0,
                'rating' => 0.00,
                'reviews_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
